In [41]:
a=set(['dog', 'cat', 'hen', 'horse', 'pig'])

In [42]:
import numpy as np

In [17]:
type(a)

set

In [21]:
b=dict()

In [23]:
type(b)

dict

In [25]:
c=dict((enumerate(a)))

In [28]:
print(c)

{0: 'horse', 1: 'hen', 2: 'cat', 3: 'pig', 4: 'dog'}


In [31]:
print(enumerate(a))

In [44]:
arr=np.array([1,2,3,4,5,6])

In [38]:
arr2=arr[2:5]

In [52]:
arr3=arr.reshape((2,-1))

In [53]:
print(arr3)

[[1 2 3]
 [4 5 6]]


In [60]:
arr4=arr[0:2]

In [62]:
print(arr4)

[1 2]


In [64]:
arr3[0:2,1]

array([2, 5])

In [89]:
print(arr3[0:1,0:2])

[[1 2]]


In [90]:
print(arr3[0:])

[[1 2 3]
 [4 5 6]]


In [97]:
print(arr3[:,-1])
print(arr3[:,:-1])

[3 6]
[[1 2]
 [4 5]]


In [98]:
print(arr3[:,1:])

[[2 3]
 [5 6]]
