In [39]:
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit
x = np.array([[1, 2], [3, 4], [1, 2], [3, 4],[3,4],[4,3]])
print(x)
y = np.array([0, 0, 1, 1,0,0])
ss = StratifiedShuffleSplit(n_splits=1, test_size=0.5, random_state=0)

[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [3 4]
 [4 3]]


In [27]:
train_index, test_index = next(ss.split(x, y))

In [29]:
print(train_index,test_index)

[4 2 5] [3 1 0]


In [38]:
splitter = ss.split(x, y)
train_i, val_i =next(ss.split(x, y))
print(train_i, val_i)
halfval_i=int(len(val_i)/2)
print(halfval_i)
val_i, test_i = val_i[:halfval_i],val_i[halfval_i:]
print(val_i,test_i)

train_x, train_y = x[train_i],y[train_i]
val_x, val_y = x[val_i],y[val_i]
test_x, test_y = x[test_i],y[test_i]

[4 2 5] [3 1 0]
1
[3] [1 0]


In [33]:
print("Train shapes (x, y):", train_x.shape, train_y.shape)
print("Validation shapes (x, y):", val_x.shape, val_y.shape)
print("Test shapes (x, y):", test_x.shape, test_y.shape)

Train shapes (x, y): (3, 2) (3,)
Validation shapes (x, y): (1, 2) (1,)
Test shapes (x, y): (2, 2) (2,)


In [46]:
print(train_y,type(train_y))

[0 1 0] <class 'numpy.ndarray'>


In [45]:
print(np.array([3,3 ,3]))

[3 3 3]
