In [1]:
token_dict={".":"||Period||"}

In [3]:
import numpy as np

In [5]:
a=np.array([1,2,3])

In [10]:
np.array([a,[3,4,5]])

array([[1, 2, 3],
       [3, 4, 5]])

In [8]:
token_dict

{'.': '||Period||'}

In [11]:
dict1=dict()

In [15]:
x=np.arange(9)

In [17]:
np.split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [20]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
y=x.reshape(3,-1)

In [30]:
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
print(np.split(y,3,1))

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [84]:
int_text=["a",2,3,4,5,6,7,8,8,9,9,0,0,0,8,7,6,5,4,4,5,6]
batch_size=3
seq_length=2
print(len(int_text))
num_batch=len(int_text)//(batch_size*seq_length)
print("num_batch=",num_batch)
inputs=np.array(int_text[:num_batch*batch_size*seq_length])
print(num_batch*seq_length)
print("inputs=",inputs,"len=",len(inputs))
inputs = np.split(inputs.reshape(batch_size,-1), num_batch, 1)

22
num_batch= 3
6
inputs= ['a' '2' '3' '4' '5' '6' '7' '8' '8' '9' '9' '0' '0' '0' '8' '7' '6' '5'] len= 18


In [85]:
targets1=int_text[:num_batch*batch_size*seq_length]

In [86]:
targets1

['a', 2, 3, 4, 5, 6, 7, 8, 8, 9, 9, 0, 0, 0, 8, 7, 6, 5]

In [87]:
targets2=int_text[:num_batch*batch_size*seq_length-1]

In [88]:
print(targets2)

['a', 2, 3, 4, 5, 6, 7, 8, 8, 9, 9, 0, 0, 0, 8, 7, 6]


In [89]:
print(int_text[0])

a


In [91]:
targets3=targets2.append("b")

In [93]:
print(targets3)

None


In [99]:
print(int_text[:3]+[int_text[0]])

['a', 2, 3, 'a']


In [1]:
import tensorflow as tf